disabled_rules: # rule identifiers to exclude from running
- force_cast
- force_unwrappingitespace
- identifier_name
- force_try
- trailing_whitespace

force_unwrapping: warning

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

line_length: 250
